aiohomekit/crypto/srp.py
Replace usage of crypto library to be compatible with Windows
=> fix Jc2k/aiohomekit#12

aiohomekit/protocol/statuscodes.py, tests/test_statuscodes.py
=> Handle status codes that are returned as positive numbers

aiohomekit/controller/ip/pairing.py, tests/accessoryserver.py, tests/test_ip_pairing.py
Fixes https://github.com/home-assistant/core/issues/37996
=> Subscribe characteristics one at a time to match iOS behavior

pyproject.toml
[`poetry-core`](https://pypi.org/project/poetry-core/) contains the build part of the `poetry` module.
=> Switch to poetry_core

aiohomekit/controller/ip/connection.py, poetry.lock, pyproject.toml, tests/accessoryserver.py
See https://github.com/home-assistant/core/issues/52642
=> Use commentjson when parsing JSON from devices, as it may contain trailing commas

aiohomekit/controller/ble/pairing.py
Call `self.client.start_notify` for subscriptions, and poll every time we get one. This is a bit better than a disconnected event as we can do a targetted poll.
This was a little bit annoying, as you can't really reuse a `BleakClient`. So now we instance of `BleakClient` every time we get disconnected. This is probably slower but works reliably so far.
See:
* https://github.com/hbldh/bleak/issues/762
* https://github.com/hbldh/bleak/pull/763
=> Implement connected events for HAP BLE

aiohomekit/controller/controller.py
There was an await missing when calling `discover_ip`
=> Add missing await

aiohomekit/model/characteristics/characteristic.py
- I'm working through reducing the memory needed so my RPi3b test target doesn't run out of memory anymore
Import distutils brings in ~82 modules.
```
"setuptools._distutils": {
"__type": "<class 'module'>",
"repr": "<module 'distutils' (/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/setuptools/_distutils/__init__.py)>"
},
"distutils.debug": {
"__type": "<class 'module'>",
"repr": "<module 'distutils.debug' from '/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/setuptools/_distutils/debug.py'>"
},
"distutils.errors": {
"__type": "<class 'module'>",
"repr": "<module 'distutils.errors' from '/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/setuptools/_distutils/errors.py'>"
},
"getopt": {
"__type": "<class 'module'>",
"repr": "<module 'getopt' from …
```
=> Avoid importing distutils

aiohomekit/zeroconf/__init__.py, tests/test_crypto_chacha20poly1305.py, tests/test_zeroconf.py
F i x e s #https://github.com/home-assistant/core/issues/67665
=> Fix zeroconf lookups when the device id is UPPER case

aiohomekit/controller/ip/pairing.py
=> Fix set changed during iteration during subscriptions

aiohomekit/controller/ip/connection.py
=> Fix reconnect race

aiohomekit/controller/ble/client.py, aiohomekit/controller/ble/pairing.py
See https://github.com/hbldh/bleak/issues/837
=> Fix BLE failing to write on M1 macs

aiohomekit/controller/ble/client.py, aiohomekit/controller/ble/pairing.py
This should fix the older eve sensors.
Sorry about pushing the WIP of this to main by accident...long week
=> Implement TLV reassembly during pairing

aiohomekit/controller/ble/pairing.py
fixes #158
Seems to be working now 
`2022-08-17 19:07:20.581 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Eve Room AE92 (FC:04:14:94:96:3E): BLE device changed from FC:04:14:94:96:3E (/org/bluez/hci1/dev_FC_04_14_94_96_3E) to FC:04:14:94:96:3E (/org/bluez/hci0/dev_FC_04_14_94_96_3E); closing connection`
```
2022-08-17 19:12:39.286 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] VOCOlinc-VS1-1857C6 (EA:03:18:99:96:D5): BLE device changed from EA:03:18:99:96:D5 (/org/bluez/hci1/dev_EA_03_18_99_96_D5) to EA:03:18:99:96:D5 (/org/bluez/hci2/dev_EA_03_18_99_96_D5); closing connection
2022-08-17 19:13:20.094 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 6JO2 (DC:5E:F9:CF:76:EB): BLE device changed from DC:5E:F9:CF:76:EB …
```
=> Fix roaming between bluetooth adapters

aiohomekit/controller/ble/connection.py, aiohomekit/controller/ble/discovery.py, aiohomekit/controller/ble/pairing.py, poetry.lock, pyproject.toml
Allows the retry connector to check if the BLEDevice has changed between attempts and recreate the client
=> Add support for updating the ble device during the connection process

aiohomekit/controller/ble/bleak.py
=> Handle EOFError from dbus

poetry.lock, pyproject.toml
=> Bump bleak-retry-connector to 1.13.0

aiohomekit/controller/ble/pairing.py
- We will reconnect with the new one the next time, however if the device is already connected there is no reason to switch until the next time.
Fixes #174
=> Leave connection open if ble device changes

aiohomekit/crypto/srp.py
=> Only calculate the session key once for SRP

aiohomekit/controller/ble/bleak.py, aiohomekit/controller/ble/client.py, aiohomekit/controller/ble/pairing.py, poetry.lock, pyproject.toml
=> Handle additional bleak exceptions

aiohomekit/controller/abstract.py, aiohomekit/controller/ble/pairing.py, aiohomekit/controller/coap/connection.py, aiohomekit/controller/coap/pairing.py, aiohomekit/controller/ip/pairing.py, tests/test_controller.py, tests/test_ip_pairing.py
=> Shutdown pairings when remove_pairing is called

aiohomekit/controller/ble/client.py
We need to backoff a bit on error to allow the device time to disconnect since otherwise the retry is in-effective
Once we are no longer backporting changes to HA 2022.10.x we can drop the retry_bluetooth_connection_error and bump bleak-retry-connector which now provides this
decorator so we do not have to maintain it here which is tracked via https://github.com/Jc2k/aiohomekit/issues/192
fixes #186
=> Implement a backoff in the bluetooth retry to allow the disconnected callback to fire

aiohomekit/controller/ble/client.py, aiohomekit/controller/ble/discovery.py, aiohomekit/controller/ble/pairing.py, poetry.lock, pyproject.toml
Shifts the maint burden to the lib which already has tests for this
=> Switch to using retry_bluetooth_connection_error from bleak-retry-connector

aiohomekit/controller/ble/bleak.py, aiohomekit/controller/ble/pairing.py, aiohomekit/model/__init__.py, aiohomekit/model/characteristics/characteristic.py
=> Save handle when fetching the gatt database

aiohomekit/controller/ble/discovery.py
=> Reset connection during pairing on failure to get services correctly

aiohomekit/controller/ble/pairing.py
=> Only check the gsn once after a characteristic has changed while connected

aiohomekit/controller/ble/pairing.py
We didn't have a way to tell before, but now that we have these values we can use them.
fixes #221
=> Only update characteristics that support disconnected events when processing disconnected events

aiohomekit/controller/ble/pairing.py
=> Ensure temporary subscribe failures do not results in failure to setup the accessory

aiohomekit/controller/ble/pairing.py
=> Fallback to disconnected events if we cannot decrypt the notification

aiohomekit/controller/ble/pairing.py, aiohomekit/model/__init__.py, aiohomekit/model/characteristics/characteristic.py, aiohomekit/model/services/service.py, tests/test_model.py
https://github.com/Jc2k/aiohomekit/pull/237/files#r1019213551
=> Reduce some linear searches to find aid and iids

aiohomekit/controller/ble/bleak.py
=> Update BLE mtu discovery code for newer bleak

aiohomekit/controller/ble/client.py, aiohomekit/controller/ble/pairing.py
We were reading the descriptor to get the iid every time 😢
=> Speed up BLE pair verify resume

aiohomekit/characteristic_cache.py, aiohomekit/controller/abstract.py, aiohomekit/controller/ble/controller.py, aiohomekit/controller/ble/manufacturer_data.py, aiohomekit/controller/ble/pairing.py, aiohomekit/model/__init__.py, tests/test_model.py
=> Restore GSN between restarts

aiohomekit/zeroconf.py
issue report https://github.com/home-assistant/core/issues/86083
=> Ignore invalid zeroconf names when considering to fetch service info

aiohomekit/model/characteristics/const.py
See https://github.com/home-assistant/core/issues/94754.
=> Add enum values for air quality

aiohomekit/controller/ble/client.py, aiohomekit/controller/ble/discovery.py
=> Clear GATT cache during discovery pairing if a service is missing

aiohomekit/controller/ble/pairing.py, aiohomekit/model/characteristics/__init__.py
related issue https://github.com/home-assistant/core/issues/97871
intended use case https://github.com/home-assistant/core/pull/97877
=> Make a constant for EVENT_CHARACTERISTICS

aiohomekit/controller/ble/pairing.py
fixes (after bump) https://github.com/home-assistant/core/issues/98488
=> Ignore iid zero when fetching the GATT database

aiohomekit/utils.py
This is going to require some more refactoring to make it work
revert it for now
partial revert of #323
=> Reverting adding typing return to clamp_enum_to_char

aiohomekit/controller/ip/pairing.py
The check to see if a device was already connected was inside an asyncio.timeout block. This has the overhead of creating and canceling a timer in the event loop every time it was run. Add a guard before the timeout to avoid this when already connected
=> Avoid creating TimerHandle when already connected

aiohomekit/testing.py
For https://github.com/home-assistant/core/pull/110334.
=> Change test pairing type when thread_provision called

aiohomekit/model/characteristics/const.py
Adding per https://github.com/home-assistant/core/pull/128618
=> Add current and target fan state enums

aiohomekit/model/characteristics/__init__.py, aiohomekit/model/characteristics/const.py
Per some additional details from #382
=> Add fan state enums to __init__

aiohomekit/controller/ip/connection.py
see https://github.com/home-assistant/core/issues/123456
=> Rework IP connections to provide more error details

.github/workflows/release.yml
Might take a few iterations to get everything working correctly so please bear with me though the noise
=> Modernize release workflow and switch to trusted publishing

poetry.lock, pyproject.toml
=> Replace black with ruff in dev deps
