- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/discovery.py
- aiohomekit/controller/ip/pairing.py
- aiohomekit/controller/pairing.py
- aiohomekit/testing.py
- tests/conftest.py
@bdraco I thought about it some more and we didn't take into account [this](https://github.com/Jc2k/aiohomekit/blob/master/aiohomekit/controller/ip/connection.py#L530) case.
That's one of the ones that i'd like to be able to get rid of in the long run (or at least not call as often), but right now it's needed for some devices to stay working for more than a day.
The most natural way to get to the zeroconf_instance from that part of the code would be if there was a zeroconf_instance on controller i think, so thats what this PR does.
What do you think?
> Controller takes a zeroconf_instance

- aiohomekit/controller/controller.py
- aiohomekit/zeroconf/__init__.py
- tests/conftest.py
- tests/test_controller.py
```
2020-07-10 16:03:15 ERROR (MainThread) [aiohttp.server] Error handling request
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line …
```
> Remove stray zeroconf argument

- LICENSE.md
Shipping the license is a requirement for distribution packages. This is something that would come up during th Fedora review process.
It would be nice if you could publish a new release after merging this? Thanks
> Add license text

- aiohomekit/model/characteristics/characteristic_types.py
- aiohomekit/model/services/service.py
- tests/fixtures/vocolinc_flowerbud.json
- tests/test_model.py
[This product](https://www.vocolinc.com/products/flowerbud-smart-diffuser) has some custom characteristics to operate as a diffuser, despite being classified as a humidifier. This adds the ability to use these characteristics.
> add vocolinc flowerbud chars

- aiohomekit/zeroconf/__init__.py
- tests/test_zeroconf.py
fixes https://github.com/home-assistant/core/issues/45199
> Handle incomplete ServiceInfo properties in async_find_data_for_device_id

- aiohomekit/controller/ip/zeroconf.py
- aiohomekit/zeroconf/__init__.py
- poetry.lock
- pyproject.toml
- tests/accessoryserver.py
- tests/test_zeroconf.py
Fixes https://github.com/home-assistant/core/issues/50534
Requires https://github.com/jstasiak/python-zeroconf/pull/356
Since there is a ServiceBrowser already running collecting the records in HomeAssistant everything is now near instant similar to the experience the user would get in the Home app:
> Load from the zeroconf cache when a ServiceBrowser for _hap is running

- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/pairing.py
- tests/conftest.py
- tests/test_ip_pairing.py
Provide a `reconnect_soon` function that will reconnect soon by canceling any waits (sleeps) in the reconnect loop or starting a new reconnect attempt.
Send an empty event on reconnect to ensure the consumer of the API knows the device is back online.
Testing Steps:
- Unplug device
- Restart Home Assistant, entity is unavailable
- Open Mac discovery app and home assistant windows near each other
- Watch device appear in discovery app (mdns announcement) and Home Assistant shows the entity available in near real time
- Unplug device, wait 10 minutes (long enough for the mdns ttl to expire), entity device is unavailable
- Open Mac discovery app and home assistant windows near each other
- Watch device appear in discovery app (mdns announcement) and Home Assistant shows the entity available …
> Provide reconnect_soon to integrate discovery

- aiohomekit/controller/ip/pairing.py
- aiohomekit/http/response.py
- tests/accessoryserver.py
- tests/test_http_response.py
As https://github.com/Jc2k/aiohomekit/issues/10 is still not viable, this continues to adapt our internal parsing.
This may be a fix for https://github.com/home-assistant/core/issues/46785.
This is a pretty core part of aiohomekit, changes here could subtly break things for many real world devices. So i've treated lightly. I changed the chunked encoding handling as little as possible while pulling it out of the header parsing code.
If there is a new line in the body it hits the bit of code inside the while loop.
```
if self._content_length > -1:
self.body += self._raw_response
self._raw_response = bytearray()
```
The blindly appends ALL the remaining buffer, even if content length was 0. Crucially it might take data it doesn't own, corrupting the parser state. The buffer is now empty and …
> Better handling of newlines inside http response body

- aiohomekit/zeroconf/__init__.py
- tests/test_zeroconf.py
See https://github.com/home-assistant/core/issues/51391.
> Some HomeKit devices use C# instead of c# in their mdns metadata.

- aiohomekit/controller/ip/discovery.py
- aiohomekit/controller/ip/pairing.py
- aiohomekit/enum.py
- aiohomekit/model/__init__.py
- aiohomekit/model/characteristics/characteristic.py
- aiohomekit/model/services/service.py
- aiohomekit/protocol/statuscodes.py
- tests/accessoryserver.py
- tests/test_enum.py
- tests/test_ip_pairing.py
- tests/test_model.py
- tests/test_statuscodes.py
This PR tracks the last characteristic state as `Characteristic.status`. This is a `HapStatusCode`, a new enum type that replaces the messier `HapStatusCodes` class. The old code wasn't useful for linting/code completion, the new enum type is.
It also adds a `bool` to `Characteristic`, `Service` and `Accessory` that returns `true` if the last `Characteristic.status` isn't `HapStatusCode.UNABLE_TO_COMMUNICATE`. For `Service` and `Accessory` i'm using `all()` to consider the state of all accessories beneath that `Service`/`Accessory`.
I considered making `available` `true` if `status == HapStatusCode.SUCCESS`, but ultimately couldn't decide if that was better or worse.
This should provide enough information to fix https://github.com/home-assistant/core/issues/51077, and leaves some room for …
> Track characteristic status

- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/zeroconf.py
- aiohomekit/zeroconf/__init__.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_zeroconf.py
Needs zeroconf 0.32.0 which should hopefully be released soon.
With zeroconf 0.32.0, a new `AsyncServiceBrowser` has been introduced.  This PR teaches aiohomekit about it so it does not fallback to slow discovery because it only knew about `ServiceBrowser`
This should fix all the inconsistencies with devices that don't provide the A records in the additionals fields when requesting PTRs
Fixes https://github.com/home-assistant/core/issues/51851
> Update to use AsyncZeroconf

- aiohomekit/zeroconf/__init__.py
- tests/test_zeroconf.py
When a ServiceBrowser is running, we check the cache for existing
_hap._tcp.local. entries. The cache enumeration failed to exclude
_hap._tcp.local. itself (service type with no name) which meant
extra unneeded questions for _hap._tcp.local. itself would be asked
along with each NAME._hap._tcp.local. that needed to be refreshed.
> Exclude _hap._tcp.local. when enumerating the zeroconf cache

- aiohomekit/zeroconf/__init__.py
- tests/test_zeroconf.py
- Tado devices (maybe others) will not respond to the lowercase name
so we will use the name that was received on the wire
> Ensure mdns questions use the same case as received on the wire

- aiohomekit/zeroconf/__init__.py
- tests/test_zeroconf.py
The async version was being passed instead of the underlying version 🤦 
When I was doing development it worked this way, but I changed it before release for backwards compat and forgot to fix this when I updated the PR, and it just happened to work because MagicMock was a bit too magic and the devices I were testing with were already in the cache.
> Ensure the correct zeroconf object is passed to AsyncServiceBrowser

- aiohomekit/controller/ip/pairing.py
- tests/accessoryserver.py
- tests/test_ip_pairing.py
@bdraco - what do you think of this? This is for https://github.com/home-assistant/core/issues/52680. Normally i'd fix this on the HA side. In fact I did at first, but it's kind of hard to test there.
The alternative would be to extend the test helpers to make it easier to check the API calls we make from HA tests.
Or make them throw an error and fail if they were called with poor quality input parameters.
> Workaround for https://github.com/home-assistant/core/issues/52680

- aiohomekit/controller/ip/connection.py
- aiohomekit/hkjson.py
- tests/test_hkjson.py
- We try to use json.loads first and fallback to commentjson
if we get a decode error to ensure that only devices that
have the trailing commas have to pay the performance hit.
> Abstract json loading into aiohomekit.hkjson

- aiohomekit/model/characteristics/characteristic_types.py
I have changes to homekit_controller too but it requires these changes... Should I wait until these changes are released on Pypi so I can update the required version in homekit_controller before opening a PR over there?
This change exposes the Update and Setup custom characteristics from Home Accessory Architect.
Addresses https://github.com/RavenSystem/esp-homekit-devices/issues/1441
> feat: add vendor characteristics for Home Accessory Architect

- aiohomekit/model/characteristics/data.py
- scripts/generate_metadata.py
Without this, the HAP/CoAP Nanoleaf Essentials bulb was being sent
hue/sat values with high precision, against the spec step value.
> Fix step value

- aiohomekit/controller/ip/connection.py
- aiohomekit/protocol/__init__.py
This will allow other keys beyond the current two to be derived.
> Return a key derivation function as a result of pair-verify

- aiohomekit/tlv8.py
- tests/test_tlv8.py
This allows dataclasses to have supporting fields.
> Ignore tlv8 dataclass fields marked with init=False

- aiohomekit/controller/coap/connection.py
- aiohomekit/controller/coap/pdu.py
- tests/test_controller_coap_pdu.py
> PDU status custom errors

- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/connection.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/crypto/hkdf.py
- aiohomekit/protocol/__init__.py
- aiohomekit/protocol/tlv.py
- tests/accessoryserver.py
- tests/test_crypto_hkdf.py
The pair resume protocol can restore a session without new ECC computations, significantly speeding up re-connection time.
> BLE Pair-Resume

- aiohomekit/__main__.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
- tests/test_ip_pairing.py
They aren't use in HA and only IP implements them. They would be annoying to add to BLE, you should just look in the char cache.
> Remove get_characteristic kwargs

- aiohomekit/__main__.py
- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/controller.py
- aiohomekit/controller/coap/controller.py
- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/controller.py
- aiohomekit/testing.py
- tests/conftest.py
- tests/test_controller.py
Can now look up known pairings via device id (`controller.pairings`) or via alias (`controller.aliases`).
In Home Asssistant we use the device id as the alias so its a bit of a no-op there.
Each backend tracks its own pairings. Right now a pairing will only be loaded into the backend it was paired with, but this sets the scene for when the top layer is potentially dynamically switching as needed.
> self.pairings is via hkid not alias

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/controller.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/controller.py
- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/controller.py
BLE HAP has 2 mechanisms for triggering events, connected and disconnected notifications.
Disconnected notifications use a number in the BLE advertising metadata. When that number increments an event has happened. The number won't increment again until the characteristics have been read, and it won't increment while you are connected.
This PR introduces a hook where BLE advertising data can be checked for these kinds of changes.
The disconnected mechanism doesn't tell us which characteristic changed, so we poll and notify on all subscriptions.
> Support for BLE disconnected events

- aiohomekit/controller/ip/connection.py
- aiohomekit/crypto/__init__.py
- aiohomekit/crypto/chacha20poly1305.py
- aiohomekit/protocol/__init__.py
- poetry.lock
- pyproject.toml
- tests/accessoryserver.py
- tests/test_crypto_chacha20poly1305.py
I built this for the other side of the house since I was annoyed at how long it took my phone to switch over from Mobile to WiFi and wanted to decrease the latency. It also seems to fix the Home app stalling out on iOS 16 betas when using them with Home Assistant's HomeKit integration.
- ChaCha20Poly1305 recreates the ctx every time its called which
is an expensive operation. This makes quite a bit of difference
when encrypting large blocks of data (camera images) since each
block had to create a new context. cryptography does this because
it needs calls to ChaCha20Poly1305 to be threadsafe at the cost
of performance. Since we are using asyncio we can avoid the
overhead of recreating the context every time since the encryptor
and decryptor are never called from different threads
> Use ChaCha20Poly1305Reusable for encryption

- poetry.lock
- pyproject.toml
- There was a [small typing fix ](https://github.com/bdraco/chacha20poly1305-reuseable/compare/v0.0.3...v0.0.4)for the lib, and I realized
I should have added it with >=
Fixes
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiohomekit 0.7.19 requires chacha20poly1305-reuseable<0.0.4,>=0.0.3, but you have chacha20poly1305-reuseable 0.0.4 which is incompatible.
```
> Change chacha20poly1305-reuseable target to >=

- aiohomekit/controller/ble/structs.py
- aiohomekit/tlv8.py
Fixes
```
022-07-16 11:37:53.464 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 372, in async_step_pair
return await self._entry_from_accessory(pairing)
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 484, in _entry_from_accessory
name = await pairing.get_primary_name()
File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/abstract.py", line 115, in get_primary_name
accessories = await self.list_accessories_and_characteristics()
File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 86, …
```
> Fix decoding kTLVHAPParamGATTUserDescriptionDescriptor

- aiohomekit/controller/ble/pairing.py
Fixes
```
2022-07-16 15:56:48.625 ERROR (MainThread) [aiohomekit.utils] Failure running background task: Task-23737
File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/utils.py", line 28, in _handle_task_result
task.result()
File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 503, in _async_start_notify_subscriptions
await self._async_start_notify(iid)
File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 285, in _async_start_notify
await self.client.start_notify(endpoint, _callback)
File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak/backends/corebluetooth/client.py", line 385, in …
```
> Fix race in subscribing to chars

- aiohomekit/controller/ble/pairing.py
- This is no longer needed after the changes in
ef9ebef8674bfd10c73affa298aaac0e21f7d7e4
> Remove pair verify fallback from BLE

- aiohomekit/controller/ble/pairing.py
Dbus is noisy and gives us a lot more data than we want
```
2022-07-16 19:54:45.471 DEBUG (MainThread) [bleak.backends.bluezdbus.scanner] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_DC_39_FF_03_B5_97/service004d/char0056): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'G\xbfP\x90Bq\x00<\x8d\xa0\xc9\xa2\x82\x85D\xbb\x8bp\x9e\xe9\x15\x95\xd8:')>}, []]
2022-07-16 19:54:45.473 DEBUG (MainThread) [bleak.backends.bluezdbus.scanner] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_DC_39_FF_03_B5_97/service004d/char0056): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'G\xbfP\x90Bq\x00<\x8d\xa0\xc9\xa2\x82\x85D\xbb\x8bp\x9e\xe9\x15\x95\ …
```
> Fix overly aggressive polling on dbus based systems

- aiohomekit/controller/ble/connection.py
- aiohomekit/controller/ble/controller.py
- aiohomekit/controller/ble/discovery.py
- aiohomekit/controller/ble/pairing.py
- If we pass a BLEDevice bleak does not need to make a new
scanner under the hood
> Use BLEDevice instead of address for bleak

- aiohomekit/controller/ble/controller.py
Fixes
```
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 249, in async_setup
await async_get_controller(hass)
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/utils.py", line 45, in async_get_controller
await controller.async_start()
File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/controller.py", line 101, in async_start
await self._async_register_backend(
File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/controller.py", line 81, in _async_register_backend
self._transports.append(await self._tasks.enter_async_context(controller))
File …
```
> Ensure missing dbus is trapped at startup via FileNotFoundError

- aiohomekit/__main__.py
- aiohomekit/characteristic_cache.py
- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/pairing.py
- aiohomekit/hkjson.py
- aiohomekit/model/__init__.py
- poetry.lock
- pyproject.toml
I finally got enough hk devices on my network that I was
noticing the json overhead. Now that HASS supports orjson
we can use that instead
> Move all json/encode to hkjson, use orjson

- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/ble/structs.py
- Remove notify workaround since we are now using
a new BleakClient object every time and the problem
goes away
- Fix missing minStep/minValue/maxValue resulting in
unexpected errors when changing color temp (etc)
Fixes
```
2022-07-25 17:01:26.391 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [4449491824] Nanoleaf Light Bulb (C8F2A86D-F301-67C3-48AE-EC9280F5A18C): PDU status was not success: Invalid request (6)
File "/Users/bdraco/home-assistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/Users/bdraco/home-assistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/Users/bdraco/home-assistant/homeassistant/core.py", line …
```
> Small fixes for BLE devices

- aiohomekit/controller/ble/structs.py
With `from __future__ import annotations` seeing the below.
The deserialize function has some magic with `__mro__` that doesn't seem to play nice.
Revert to using legacy typing for now until we can figure out what the root cause is.
> 
> ```
> 2022-07-26 02:21:14.700 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 481, in async_step_pair
>     self.finish_pairing = await discovery.async_start_pairing(self.hkid)
>   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 63, in _async_wrap
>     return await func(*args, **kwargs)
>   File …
```
> Use legacy typing to resolve tlv exception

- poetry.lock
- pyproject.toml
Replaces https://github.com/Jc2k/aiohomekit/pull/126 with the dep bump only
> Bump bleak-retry-connector to 1.1.1 to fix a dbus hang

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/model/__init__.py
- aiohomekit/model/characteristics/characteristic.py
Since the device presented a config number of 0 we never fetched the values because we believed we were already up to date since the default was 0
Fixes #128
> Fix pairing with devices that use a config number of 0

- aiohomekit/model/__init__.py
- aiohomekit/model/entity_map.py
This is the fix for one of only 2 failures left when turning on strict mypy for hkc's config_flow module.
> Add typing hints to accessories.serialize()

- aiohomekit/controller/abstract.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/pairing.py
This fixes reconnect_soon to have a return type. This I think means we can turn on the strictest mypy settings in home assistant for the config_flow module.
While i was there I tweaked reconnect_soon in CoAP so that connection object always get passed the latest ip/port (in case the accessory changed ip but we haven't noticed yet). This was the latest outstanding CoAP issue i knew about before the recent refactoring work. This is kinda of hacky, but what the IP backend is doing AFAICT. Ideally we'd have it pull the latest details out of the zeroconf cache directly itself rather that relying on the pairing_data changing under us.
> Fix typing of reconnect_soon

- aiohomekit/controller/ble/discovery.py
- aiohomekit/protocol/__init__.py
- aiohomekit/protocol/tlv.py
- tests/test_protocol_tlv.py
Trying to work out 
https://github.com/Jc2k/aiohomekit/issues/136
This make it a bit easier to read
```
2022-08-07 12:40:15.282 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.127: raw response: bytearray(b'\x06\x01\x02\x03 \xa41\xbc\x82\xce\x8a\x13,e/#Cw\xa7:\xcb\x0c\x08\xee9\xf2\xb1\xfaB\xc3\xd4\xa0O\xf1\x14\xa6\x00\x05e\x9c\xccs\x13\x85\xf4\xba\xb6\x9f"\xcc\xf1\xe3a\xbd+\xc9\x9f\xfe\x12c+\xd1\x03tg\xed\xc1\xde\xe3\xefo\xc6Ur\xb3\r\xee;\xde\xd6\x06\xeb`\xb9%\xa1\r\xfc\xb6\xdb4C+c\x1c\xb6^\x18\x85>\xfc\x14=\r\x93e\x91ON_~\xd5\xe7du&\xc4\xe2\xc2g\xbc\xc5\xb6u\x95\xb7\x1a\x1f\x8bN\x08\xe5\x89\xcd\x0f\x18\xa8\xc0\xf7}')
2022-08-07 12:40:15.283 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
6 (State): (1 bytes/<class 'bytearray'>) 0x02
3 (PublicKey): (32 …
```
> Improve TLV decode debug logging

- aiohomekit/controller/ble/bleak.py
- aiohomekit/controller/ble/const.py
These turned out to be asymmetric and we will need
to wait for https://github.com/hbldh/bleak/issues/925
to be implmented to get the mtu with bluez.
> Drop mtu auto discovery

- aiohomekit/controller/ble/bleak.py
- aiohomekit/controller/ble/client.py
- aiohomekit/controller/ble/discovery.py
- aiohomekit/controller/ble/pairing.py
This is working with the current version of bleak as well and restores the performance that was lost in https://github.com/Jc2k/aiohomekit/pull/139
Also drops `.handle` calls since https://github.com/hbldh/bleak/issues/888
Needs https://github.com/hbldh/bleak/pull/930 for `max_write_without_response_size` but we can already get the MTU since the dict is accessible already.
> Add support for bleak max_write_without_response_size and current bleak MTU

- aiohomekit/controller/ble/structs.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/zeroconf.py
The original plan for aiohomekit 1.0 was going to be that we attched to the zeroconf instance in the ZeroconfController and notified pairings when it spotted the ip/port changing. This was pushed back, so this needs restoring for now.
> Fix regression in aiohomekit 1.0.0 where IP/port changes are not picked up

- aiohomekit/controller/ble/bleak.py
Trying to work out https://github.com/Jc2k/aiohomekit/issues/135
> Improve error logging when a char or service is missing

- aiohomekit/controller/ble/bleak.py
- aiohomekit/controller/ble/connection.py
- aiohomekit/controller/ble/pairing.py
- poetry.lock
- pyproject.toml
We now cache the services when reconnecting to reduce the time before we can start talking to the accessory.
The cache is never used when we need to fetch the GATT database or the ble device has changed
between connections.
The naïve address check has been replaced with the `ble_device_has_changed` helper which knows about
adapter changes.
> Implement bluetooth service caching

- poetry.lock
- pyproject.toml
Fix for devices that go in and out of range frequently
> Bump bleak-retry-connector to 1.7.2

- aiohomekit/crypto/srp.py
- aiohomekit/protocol/__init__.py
- tests/accessoryserver.py
- tests/test_crypto_srp.py
Allows LIFX beam to pair
Refactoring to reduce int to bytes conversion to avoid the risk of random pairing failures when there are leading zeros in the key or salt since they would end up converted to short bytearrays
> Fix missing padding in SRP

- aiohomekit/controller/ble/discovery.py
- aiohomekit/controller/ble/manufacturer_data.py
- aiohomekit/controller/ble/pairing.py
We pass the connection on to the pairing once we finish pairing, however if the device is on the edge of range and it disconnects before the next ADV is received, device is unset and we cannot reconnect.
Also log the RSSI so we get a better idea why pairing is failing.
> Fix ble device not being passed from discovery to pairing when paired

- aiohomekit/__main__.py
- aiohomekit/controller/ble/controller.py
- aiohomekit/controller/coap/connection.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/debounce.py
- aiohomekit/zeroconf.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_controller.py
- tests/test_controller_ip_controller.py
This is still a draft, and mostly to help with conversations.
It changes ZeroconfController to populate a location cache of discoveries (`self.discoveries`) and keep it up to date with the latest parsed data.
`async_find` and `async_discover` then only operate on that cache.
And active pairings also get a `_async_description_update` callback (like bluetooth) with the latest `HomeKitService`.
So far the only benefits of this are:
* The IP backend doesn't need to await to get the latest connection details as self.description will always be up to date
* The CoAP backend doesn't rely on some magic coincidentally changing dict to pick up IP changes (and i think thats broken anyway).
But i also want to make some other changes, as below. 
Make a version of `async_find` that first yields the …
> Update Zeroconf based backends to use _async_description_update

- aiohomekit/controller/coap/connection.py
A splat occurs during pair-setup when we attempt to unsubscribe from nothing.
> Fix CoAP pairing

- aiohomekit/controller/abstract.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/pairing.py
- aiohomekit/zeroconf.py
- tests/test_ip_pairing.py
This was something I wanted to do with the introduction of BLE into HA, as it was a transport specific concept. With the changes in #151 we can now fully do it.
This has no impact for BLE, which never used it. It has no impact for CoAP, which stopped using it in #151. The only impact for IP is that the "service info changed" signal now comes directly from zeroconf (via `_async_description_updated`) instead of via the config flow code in home assistant.
I also pulled the logic for detecting an ip/address change out of CoAP, as it applies to both IP based backends.
I could temporarily revert the changes to aiohomekit/controller/abstract.py to make it easier to test.
> Get rid of reconnect_soon

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
- aiohomekit/testing.py
Gets rid of `notify_config_changed` entirely, prefering to do it internally based on triggers from zeroconf.
Note that BLE had `_process_config_changed` and `_async_process_config_changed`. One was trigger by bluetooth advertisements, one was triggered by HA. I have removed an arbritary one.
The thing I'm not yet decided on how to handle is state_num. It's important that its nestled in with the c# checks as that optimises the case where both have changed. But its a waste to create a task on IP and CoAP as they don't sue state_num. Could make it a sync callback, and only create a task in the BLE backend?
> Handle zeroconf c# changes directly not via notify_config_changed

- poetry.lock
- pyproject.toml
When the device is still connected for a few ms after an abort we need to wait for it to fully disconnect
> Bump bleak-retry-connector to implement a smart backoff 

- aiohomekit/controller/coap/structs.py
Eve Energy uses TLV 11. It wasn't in the struct, so parsing exploded. This fixes that.
> Add missing TLV field

- aiohomekit/const.py
I think we are inching closer with this, so I thought i'd open up a PR to discuss the next steps.
I currently have an Eve Energy, Eve Thermo and Nanoleaf NL55 working over Thread on HA `main`, with a Homepod running as a border router.
To get all the devices onto thread the basic process I followed was:
* Pair to HomeKit with iOS
* Use Eve app to verify Thread status
* Unpair the device from iOS
* Pair with Home Assistant
For the Energy and Nanoleaf in particular, this was quite painless. And it's very similar to the process we already use when WiFi devices need the WiFi creds provisioning.
Eve Thermo was trickier. It looks like it has a bug where you can't actually unpair it over CoAP (even with iOS). So I had to disable my border routers and wait till I could "Identify" over bluetooth. …
> Enable CoAP by default

- aiohomekit/controller/ble/bleak.py
Bleak now wants the disconnected_callback in the constructor so we must pass all the kwargs for future compat
Fixes
```
Sep 26 05:03:12 homeassistant homeassistant[485]: TypeError: AIOHomeKitBleakClient.__init__() got an unexpected keyword argument 'disconnected_callback'
```
unblocks: https://github.com/Bluetooth-Devices/bleak-retry-connector/pull/49
> Passthrough kwargs to BleakClient

- aiohomekit/controller/ble/pairing.py
If we create them they will get assigned the next available one which will conflict with the actual one. We need to ignore these services as they are not homekit services but services defined by the vendor
> fix: skip services that are missing an iid

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/connection.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
- aiohomekit/testing.py
Currently we only use this value for BLE connections
The goal is to fail quickly at startup so we do not block HASS startup and let the retry logic take over after startup to get the device up and going
> Allow specifying the number of attempts with async_populate_accessories_state

- aiohomekit/controller/ble/pairing.py
If the device is asleep at startup we will not have the key when it wakes up and sends us a notification.
> Fallback to disconnected events when receiving encrypted notify without having the key yet

- aiohomekit/controller/ble/pairing.py
The spec says the accessory should implement it but the older eve room doesn't, it also doesn't implement encrypted broadcast notifications
fixes #206
> Handle accessories that are missing the the service signature char

- aiohomekit/controller/ble/pairing.py
If this turns out to be more common we will probably need a function to handle additional workarounds. Since iOS is forgiving for this we should be as well
fixes https://github.com/home-assistant/core/issues/80177
> Add workaround for older eve devices

- aiohomekit/controller/ble/pairing.py
We need to be connected for this to work. I
didn't notice this because everything else supported encrypted notify
> Fix missing decorator on get_all_protocol_params

- aiohomekit/controller/ble/pairing.py
Also fixes a race where was_connected was wrong because we were waiting for the lock and by the time is was acquired the value was stale and we had to reconnect.
Before these changes I was able to get the eve button to fallback to disconnected events.  Now I can mash it over and over and I get broadcast events for everything
Reduces the latency of disconnected events by calling the listeners after each char is read to avoid waiting for everything to be read
Ensure we re-read the GSN after starting notify and after a notify so we are always in sync
> Fix for various races with encrypted notifications

- aiohomekit/characteristic_cache.py
- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/model/__init__.py
- aiohomekit/utils.py
TLDR: This fixes battery powered BLE devices that sleep for long intervals
Some accessories will sleep for a long time and only send broadcasted events which makes them have very long connection intervals to save battery. Since we need to connect to get a new broadcast key we now save the broadcast key between restarts to ensure we can decrypt the advertisements coming in even though we cannot make a connection to the device during startup. When we get a disconnected event later we will try again to connect and the device will be awake which will trigger a full sync
Additional details: https://github.com/home-assistant/core/pull/81211
fixes #215
> Restore broadcast_key between restarts

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/bleak.py
- aiohomekit/controller/ble/client.py
- aiohomekit/controller/ble/discovery.py
- aiohomekit/controller/ble/pairing.py
- The ESP32s have unstable handles so we need another way to map services/chars on the ble stack. Since Bleak will raise BleakError if there is more than one service with the same uuid we now manually enumerate services and chars until we find a matching pair to avoid the need to use handles
- If the service + char combination is ambiguous, we will ready iids until we find a match
> Replace handle lookups with a combined service/char/iid lookup

- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/ble/structs.py
- aiohomekit/zeroconf.py
- tests/test_zeroconf.py
This should fix https://github.com/home-assistant/core/issues/80211 by replicating the old HA behaviour of dropping link local addresses.
> Ignore link local addresses

- aiohomekit/controller/ble/pairing.py
It can take 3-10s depending on how slow the ble connection is for HA to update after a successful write. This sometimes makes the switch turn back off in HA after it was successful so we should callback the change as soon as we know the OpStatus is successful to avoid the flip-flop.  With the nanoleaf devices this can even take > 10s because of how many chars need to be read to sync.
This change ensures HA more accurately reflects the state of the device since the light strip would light up and than HA changed state 10-15s later
> Notify listeners of new state on successful BLE write

- aiohomekit/zeroconf.py
- tests/conftest.py
- tests/test_controller_ip_controller.py
#228 was actually the same root cause as the issue fixed by https://github.com/jstasiak/python-zeroconf/pull/1102 and we do want `.alias` here :man_facepalming: (PTR records are the only ones that need this), but we should use `async_all_by_details` instead of `get_all_by_details` since we are calling this in `async` context.
This reverts the change in #228 and wraps it in a new function that uses `async_all_by_details` and fixes the typing.
I also rewrote the tests so they are testing closer to what is in production so we avoid patching the zeroconf cache and the patch for `aiohomekit.zeroconf.AsyncServiceInfo` is now only patching out the `async_request` call instead of the whole object so we won't regress this.
I also fixed the `test_discover_find_none` taking 10s to run.
fixes #232
> Fix initial zeroconf lookup on start take 2

- aiohomekit/controller/ble/bleak.py
- aiohomekit/controller/ble/pairing.py
Sometimes BlueZ fails to get all the services. If we disconnect and reconnect it resolves the problem.
This PR defines a wrapper that forces disconnect when the underlying code encounters a missing GATT service
or char
fixes #238
This only fixes the ones that fail to resolve sometimes unlikely #135 where they fail to resolve always.
> Force reconnect when GATT services are missing to re-resolve services

- aiohomekit/controller/ble/controller.py
- aiohomekit/controller/ble/pairing.py
Overrides the default implementation of get_primary_name
to get name from the advertisement if the
accessories are not available which happens
frequently with the ESPHome proxies because
they cannot currently connect right away again
after disconnecting.
We want to avoid raising there if possible
since this is called right after pairing
and if we raise the pairing will fail but
the device will still be paired and the user
will have to un-pair it manually with a factory
reset.
Also modifies the handle check to
handle no services being available yet.
> Improve BLE pairing reliability, especially with esp32 proxies

- aiohomekit/controller/ble/pairing.py
Found on retest of #248 in production
> Fix setting iid too late during GATT database fetching

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
- pyproject.toml
- tests/conftest.py
- tests/test_controller_coap.py
- tests/test_ip_discovery.py
- tests/test_ip_pairing.py
> Callback listeners on put for all controllers

- aiohomekit/controller/ble/client.py
This speeds up writes a bit especially with the bluetooth proxies. 
No need to wait for a response if the device supports it because we are always waiting for the read response anyways.
> Use the same gatt write logic in _write_pdu as _read_signature

- aiohomekit/controller/coap/connection.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
We only set the updated address when there was an encryption context. That meant we couldn't fix the IP if it was wrong at startup.
Fixes: https://community.home-assistant.io/t/homekit-accessory-protocol-hap-over-coap-udp-was-nanoleaf-essentials-bulb-via-thread-coap/335167/311?u=jc2k.
> CoAP: Fix recovering from incorrect IPv6 address at start

- aiohomekit/controller/ble/pairing.py
The GSN will never change while we are connceted. We must increment it ourselves when we get a GATT notify, and we must only ever do it once per session since it does not actually change in the adv until we disconnect.
This fix ensures we do not reconnect again to the device when there is no change since we did not previously increment the GSN ourselves
We also refetch the broadcast encryption key when
the GSN rolls over as a roll over invalidates the
previous key
> Fix GSN fetching logic

- aiohomekit/controller/coap/pairing.py
Initial fix was tested in connection.py, and i messed it up moving it to here - there is no self.owner in paring!
> Fix coap ip change handling

- aiohomekit/controller/ble/client.py
- aiohomekit/controller/ble/pairing.py
Reverts Jc2k/aiohomekit#261
This seems to increase the risk of `Operation failed with ATT error: 0x0e (Unlikely Error)` happening quite a bit with bluez.  Its likely making it to quick for the bluez to keep up and ending up disconnected.
I think we are stuck with a revert for now.  A bit slower and reliable is better than unexpected disconnects.  Its also less of a concern after #267 anyways.
> Revert "Speed up BLE pair verify resume"

- aiohomekit/controller/ble/pairing.py
Fixes
```
/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py:813: FutureWarning: This method will be removed future version, use the services property instead.
services = await self.client.get_services()
```
> Fix future warning about client.get_services

- aiohomekit/uuid.py
- tests/test_utils.py
In CoAP we are seeing squished UUID's like `45E5011ECB4000A80FF2603DE`. These need padding to 32 chars with leading `0` before normalising.
E.g. `45E5011ECB4000A80FF2603DE` should become `00000004-5E50-11EC-B400-0A80FF2603DE`.
Via https://community.home-assistant.io/t/homekit-accessory-protocol-hap-over-coap-udp-was-nanoleaf-essentials-bulb-via-thread-coap/335167/346?u=jc2k
> Pad short uuid with 0's

- aiohomekit/model/services/service.py
The return type for `Service.build_update` should be a list of tuples.
> Fix service build_update typing

- aiohomekit/model/characteristics/characteristic_types.py
This adds a constant for the Airversa characteristic for sleep mode. If you can point me to how I can log characteristic changes I wouldn't mind attempting to figure out what the other vendor specific keys do.
For PR verification purposes, here is the definition of this value from the device diagnostics:
```
{
"type": "00000006-5E50-11EC-B400-0A80FF2603DE",
"iid": 32842,
"perms": [
"pr",
"pw",
"ev"
],
"format": "int",
"value": 0,
"minValue": 0,
"maxValue": 1
},
```
> Add vendor extension for Airversa sleep mode

- aiohomekit/model/__init__.py
- tests/test_model.py
Since most lookups are by service_type we now store them in a dict under the hood to avoid linear searches
fixes #276
> Avoid linear searches to get services by service_type

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/controller.py
- aiohomekit/controller/ble/pairing.py
So that we can merge CoAP and BLE discoveries for the same device and so that we can migrate a BLE pairing to a CoAP pairing we should use the HAP device ID (hkid) as the key in our API, not the BLE mac address. This is needed for #148.
This PR doesn't really address the root cause, it just removes some duplicated code that incorrectly looks in `self.discoveries` for a mac address, that would always fail. So i think this PR could go out independently of the HA changes.
In addition to this PR, HA needs the following patches:
```
await self.async_set_unique_id(discovery_info.address)
self._abort_if_unique_id_configured()
```
This needs to move after parsing the advertisement and use device.id instead. It should call normalized_hkid.
It also needs a migration to fix `unique_id` on any …
> BLE should use hkid at API boundary, not MAC

- aiohomekit/zeroconf.py
- poetry.lock
- pyproject.toml
Removes the need for _first_non_link_local_address since zeroconf now guarantees LIFO order for addresses
> Bump zeroconf to 0.54.0 to fix handling server name changes

- aiohomekit/model/__init__.py
There can only be one of these so we can cache the lookup once we do it once
fixes #289
> Only lookup the accessory_information service once

- aiohomekit/controller/ip/connection.py
- aiohomekit/http/__init__.py
Should fix
```
2023-06-07 23:08:07.990 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.178.149: raw request: b'POST /pair-verify HTTP/1.1\r\nHost: 192.168.178.149\r\nContent-Length: 37\r\nContent-Type: HttpContentTypes.TLV\r\n\r\n\x06\x01\x01\x03 \xa1[\xae\xe0J\xcc\xc5{\xd2f\xb8\xfd\xfd\x11\xdb\x1bP\x8a\x93\xe8\x01\xc3\xf8\x05w\xe4\xe7\xbd9\x8c\x08E'
```
> Fix content-type on python 3.11

- aiohomekit/controller/ble/controller.py
- tests/test_controller_ble.py
The fix in #298 was not sufficient
> Fix ble controller discovery where old name is None

- aiohomekit/controller/ble/pairing.py
#197 added a check for missing handles if the user was running an older version. As its been a few months, everyone should have the missing handles populated now, and since this check is rather expensive to run every operation, we should remove it.
> Remove workaround to populate missing handles

- aiohomekit/controller/ble/client.py
- aiohomekit/controller/ble/key.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/crypto/__init__.py
- aiohomekit/crypto/chacha20poly1305.py
- aiohomekit/protocol/__init__.py
- tests/accessoryserver.py
- tests/test_coap_structs.py
- tests/test_controller_coap_pdu.py
- tests/test_controller_ip_controller.py
- tests/test_crypto_chacha20poly1305.py
- tests/test_enum.py
I was testing with some cameras and noticed the image encryption overhead was showing up in the profile
- Implement the todo to not return `False`
> Reduce memory churn and copy while decoding large payload

- aiohomekit/controller/ble/controller.py
fixes - https://github.com/home-assistant/core/issues/97592
fixes - https://github.com/home-assistant/core/issues/80851
> fix: BLE controller returning None on timeout instead of raising AccessoryNotFound

- aiohomekit/controller/ble/pairing.py
fixes (once bumped) https://github.com/home-assistant/core/issues/91686
> Handle missing perms when decoding the GATT database

- aiohomekit/utils.py
> https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task
> Important Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection
> Hold strong references to tasks

- aiohomekit/controller/ble/pairing.py
Devices should never send iid 0, but they do
related issue https://github.com/home-assistant/core/issues/99306
> Strip out iid 0 from the linked services list

- aiohomekit/controller/ip/connection.py
https://docs.python.org/3/library/asyncio-future.html#asyncio.Future
> The rule of thumb is to never expose Future objects in user-facing APIs, and the recommended way to create a Future object is to call loop.create_future(). This way alternative event loop implementations can inject their own optimized implementations of a Future object.
> Create futures with loop.create_future()

- aiohomekit/model/characteristics/characteristic.py
Currently if minStep is present but `0` it causes a division error. `0` is not a valid value for minStep, so bypass clamping as if it wasn't there at all.
Fixes https://github.com/home-assistant/core/issues/100183.
> Workaround invalid minStep values

- aiohomekit/model/__init__.py
- aiohomekit/model/characteristics/characteristic.py
- aiohomekit/protocol/statuscodes.py
- aiohomekit/testing.py
- tests/test_model.py
- tests/test_testing.py
I realized we still write state too frequently. When we do the poll if the value is the same we still callback the entity.
Will be used in https://github.com/home-assistant/core/pull/102370
> Make process_changes return a set of what actually changed

- aiohomekit/zeroconf.py
When TXT record is "\x03md=" zeroconf gives us a None. I thought that was a type violation, but that is indeed expected so update aiohomekit to cope with it.
We already have code paths to cope with missing records, so just drop empty fields so we pick up existing defaults.
> Handle Aqara sensor having invalid md=

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/connection.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
- tests/test_ip_pairing.py
- Add some missing typing
fixes home-assistant/core#103103
- coap: needed an subscriptable list
- ble: didn't care about order
- ip: didn't care about order and always converted to a set
> Ensure all transports can handle an iterable in get_characteristics

- aiohomekit/controller/ip/pairing.py
We now have multi-ip support but when I refactored, I missed some old `.host` variables in the exception text
> Fix IP exceptions referencing the old host var

- aiohomekit/controller/ip/connection.py
related issue https://github.com/home-assistant/core/issues/107137
When we added happy eyeballs, I added the port, but this seems to cause problems for some devices
> Remove port from Host header

- aiohomekit/controller/coap/connection.py
Prior to this change if a remote device stopped responding (e.g. packet loss) we would never recover - we'd just keep incrementing the encryption counter making it further and further away from the truth.
The only way to recover from this right now is to restart HA which obviously resets the encryption session.
This patch can't fix the buggy device, unstable network or packet loss that lead to a timeout in the first place but it can help things recover without needing a full HA restart.
Tested by a community member with a very unstable set of Nanoleaf devices (multiple devices go offline at same time, and with this patch they actually recover by themselves).
> Recover CoAP pairing when remote device stops responding

- poetry.lock
- pyproject.toml
This also indirectly bumps cryptography to >=42.0.0.
This fixes CI with newer versions of cryptography.
> Bumping chacha20poly1305-reuseable to 0.12.1

- aiohomekit/model/characteristics/characteristic.py
We can avoid most of the body of this function for the common case.  We call this a lot when adding entities
> Small speed up to fetch characteristic values

- aiohomekit/controller/abstract.py
- aiohomekit/controller/ble/pairing.py
- aiohomekit/controller/coap/pairing.py
- aiohomekit/controller/ip/pairing.py
Since ip pairing and coap pairings do nothing in _process_disconnected_events, make it a normal function instead and have the ble pairing create tasks as needed
> Avoid creating tasks to process zeroconf updates

- aiohomekit/controller/ip/connection.py
- tests/test_ip_pairing.py
There were two problems that prevented the IP transport from reconnecting
1. When the connection was lost, _start_connector would not try to reconnect because self.transport and self.protocol were still set which meant the connection was not full torn down and it thought it was still connected. This is fixed by clearing transport and protocol before calling _start_connector.  This meant we would never reconnect until a poll attempt which restarted the connector.
2. If a request was inflight the connection would get re-established and than the concurrency lock would prevent the pair-verify from happening. This is fixed by resolving all the futures that are waiting when the connection is lost.
> Fix IP controller not reconnecting right away

- aiohomekit/controller/ip/connection.py
If the requests hits th 30s timeout, but responds or times out at just the right time before the during the connection teardown, the future will already be resolved.
> Fix race when during timeout of IP connection request

- aiohomekit/model/characteristics/characteristic_types.py
Documenting two characteristics (one new) for Ecobee thermostat.
One thing I wasn't sure about, I added a better name for the "_TIMESTAMP" but not sure if I should just remove it instead even if that's technically a breaking change.
> Add documentation to some Ecobee characteristics

- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/connection.py
- tests/test_ip_pairing.py
With Python 3.12+ and later `transport.writelines` is implemented as [`sendmsg(..., IOV_MAX)`](https://github.com/python/cpython/issues/91166) which allows us to avoid joining the bytes and sending them in one go.
Older Python will effectively do the same thing we do now `b"".join(...)`
> Implement zerocopy writes for the encrypted protocol

- aiohomekit/__main__.py
This fixes an issue I observed locally, where running `aiohomekitctl` with any existing IP pairing would throw an error:
```
controller.py:0185 ERROR Skipped pairing: Transport IP not supported. See setup.py for required dependencies.
```
After tracing, I discovered this is because the pairings were loaded before the transports, and moving the load_data call to this new location seemed to have fixed it for me.
> Fix pairings being loaded before transports

- .github/workflows/ci.yml
Fixes
```
lintYour workflow is using a version of actions/cache that is scheduled for deprecation, actions/cache@v2. Please update your workflow to use either v3 or v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-downShow more
--
lintThe `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[lint](https://github.com/Jc2k/aiohomekit/actions/runs/13598166056/job/38019457811)
Your workflow is using a version of actions/cache that is …
```
> Modernize lint workflow

- aiohomekit/controller/ip/pairing.py
Somfy TaHoma switch homekit controller /characteristics response is: {'status': 0}
As consequence, KeyError: 'aid' is raised breaking characteristics subscriptions (poll works, push/ev does not). Fix checks for existence of aid and iid.
Once fix is applied, push/event works perfectly on Somfy TaHoma switch.
Initial error is
```
Error doing job: Task exception was never retrieved (None)
File "/srv/homeassistant/lib/python3.13/site-packages/aiohomekit/controller/ip/pairing.py", line 359, in subscribe
return await self._update_subscriptions(characteristics, True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.13/site-packages/aiohomekit/controller/ip/pairing.py", line 401, in _update_subscriptions …
```
> Fix _update_subscriptions - checking characteristic's aid and iid existence #1

- poetry.lock
- pyproject.toml
Fixes the warning
> The "poetry.dev-dependencies" section is deprecated and will be removed in a future version. Use "poetry.group.dev.dependencies" instead.
> Migrate pyproject to use newer syntax for poetry groups

- .github/workflows/release.yml
Use softprops/action-gh-release to upload the release instead Also sign them with sigstore/gh-action-sigstore-python
> Replace deprecated upload-release-asset

- aiohomekit/controller/abstract.py
- aiohomekit/controller/controller.py
- aiohomekit/controller/ip/connection.py
- aiohomekit/controller/ip/pairing.py
- If anything fails, we should still explictly shutdown the connection.
- If the device gets rediscovered after shutdown via `_async_description_update`, don't reconnect
fixes #343
> Ensure connection is always shutdown when removing a pairing

- aiohomekit/controller/ble/manufacturer_data.py
- tests/test_controller_ble_manufacturer_data.py
- Fixes #480: `struct.error: unpack requires a buffer of 6 bytes` crash
- Added buffer size validation before unpacking HomeKit BLE advertisement data
- Prevents crashes when receiving malformed or truncated Bluetooth advertisements
- Raises a descriptive `ValueError` instead of letting `struct.unpack` fail
- Added comprehensive tests for various buffer sizes (too short, almost enough, exactly enough)
- Ensures the buffer has at least 19 bytes as required by the HomeKit BLE advertisement format
> Fix struct.error when parsing corrupted BLE manufacturer data

- aiohomekit/controller/ip/pairing.py
- tests/test_controller_ip_pairing.py
- tests/test_ip_pairing.py
- Fixes `TypeError: 'bool' object is not subscriptable` when HomeKit devices return malformed responses
- Some devices (like TaHoma V2 covers) return boolean values (`true`) mixed with error dictionaries in characteristic responses
- Added type checking to skip non-dictionary values in both `put_characteristics` and `format_characteristic_list`
- Fixes #465 reported with Home Assistant's HomeKit Controller integration
- Added test cases for both functions to handle boolean values in responses
- All existing tests pass without regression
> Fix handling of malformed HomeKit responses with boolean values

- tests/conftest.py
https://github.com/pytest-dev/pytest-asyncio/pull/1106
> Stop using the deprecated event_loop fixture

- aiohomekit/controller/ble/manufacturer_data.py
- tests/test_controller_ble_manufacturer_data.py
PR #500 fixed issue #480 (struct.error crash) by requiring 19-byte BLE advertisements, but this broke Eve Thermo gen1 and Eve Room gen1 devices that only send 15-byte advertisements without the setup_hash field.
- Reduced minimum advertisement size from 19 to 15 bytes (the actual required minimum) as aiohomekit can still work without the setup hash.
- Made setup_hash field (bytes 15-19) optional, defaulting to empty bytes when absent
- Updated tests to verify both 15-byte (no hash) and 19-byte (with hash) advertisements work
- Maintains protection against corrupted data (<15 bytes) while supporting older devices
Fixes: home-assistant/core#152674
> Fix BLE advertisement parsing for older Eve gen1 devices
